### ISSUE TITLE
collapse_rows does not work when my non-collapsed columns have repeated values

### ISSUE THREAD

**Issue by JonahLong** [haozhu233/kableExtra#109]
I am relatively inexperienced with programming, so I am sorry if I am overlooking something really simple here, but I am experiencing the same issue as this person who posted recently in SE recently:  
https://stackoverflow.com/questions/47562909/error-using-kableextra-collapse-rows-with-non-unique-values-in-non-collapsed-col

collapse_rows seems to be causing an error when a table contains repeated values in non-collapsed columns.  I was able to replicate the SE poster's error with the example provided, as well as with my own dataset.  Thanks for any insight-

**Comment by haozhu233** [comment]
Hi, @JonahLong, sorry for the delay. Now this bug has been addressed in the dev version. :)

**Comment by wfulp** [comment]
I'm still getting this issue in the dev version:

```r 
library(dplyr)
library(kableExtra)

my_data <- data.frame(
  State = c('State A','State A','State B','State B'),
  City = c('City 1','City 2','City 1','City 2'),
  Value = c(4,12,4,10)
  )

kable(my_data, 'latex', booktabs = TRUE) %>%
  collapse_rows(1:2, row_group_label_position = 'stack')
```
This code does not compile, although works perfectly if I change either 4 in `Value` to another number.

**Comment by wfulp** [comment]
I am getting the exact same output, but isn't that Latex table incorrect, putting `State A` and `State B` right next to each other?

When I run the code with both 4s I get:
```
\begin{tabular}{llr}
\toprule
 & City & Value\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{State A}}\\
\hspace{1em}\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{State B}}\\
\hspace{1em} & City 1 & 4\\
\cmidrule{2-3}
\hspace{1em} & City 2 & 12\\
\cmidrule{1-3}
 & City 1 & 4\\
\cmidrule{2-3}
\hspace{1em} & City 2 & 10\\
\bottomrule
\end{tabular}
```

but which I change the second 4 to a 5 I get:
```
\begin{tabular}{llr}
\toprule
 & City & Value\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{State A}}\\
\hspace{1em} & City 1 & 4\\
\cmidrule{2-3}
\hspace{1em} & City 2 & 12\\
\cmidrule{1-3}
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{State B}}\\
\hspace{1em} & City 1 & 5\\
\cmidrule{2-3}
\hspace{1em} & City 2 & 10\\
\bottomrule
\end{tabular}
```
where the State A and State B are properly split up.

Here is my session_info:
```r
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, mingw32             
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2018-10-16                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       source                               
 backports     1.1.2   2017-12-13 CRAN (R 3.5.0)                       
 base        * 3.5.1   2018-07-02 local                                
 colorspace    1.3-2   2016-12-14 CRAN (R 3.5.0)                       
 compiler      3.5.1   2018-07-02 local                                
 crayon        1.3.4   2017-09-16 CRAN (R 3.5.0)                       
 datasets    * 3.5.1   2018-07-02 local                                
 devtools      1.13.6  2018-06-27 CRAN (R 3.5.1)                       
 digest        0.6.18  2018-10-10 CRAN (R 3.5.1)                       
 evaluate      0.12    2018-10-09 CRAN (R 3.5.1)                       
 git2r         0.23.0  2018-07-17 CRAN (R 3.5.1)                       
 glue          1.3.0   2018-07-17 CRAN (R 3.5.1)                       
 graphics    * 3.5.1   2018-07-02 local                                
 grDevices   * 3.5.1   2018-07-02 local                                
 hms           0.4.2   2018-03-10 CRAN (R 3.5.1)                       
 htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)                       
 httr          1.3.1   2017-08-20 CRAN (R 3.5.1)                       
 kableExtra  * 0.9.0   2018-10-16 Github (haozhu233/kableExtra@6e63188)
 knitr         1.20    2018-02-20 CRAN (R 3.5.0)                       
 magrittr    * 1.5     2014-11-22 CRAN (R 3.5.0)                       
 memoise       1.1.0   2017-04-21 CRAN (R 3.5.1)                       
 methods     * 3.5.1   2018-07-02 local                                
 munsell       0.5.0   2018-06-12 CRAN (R 3.5.0)                       
 pillar        1.3.0   2018-07-14 CRAN (R 3.5.1)                       
 pkgconfig     2.0.2   2018-08-16 CRAN (R 3.5.1)                       
 R6            2.3.0   2018-10-04 CRAN (R 3.5.1)                       
 Rcpp          0.12.19 2018-10-01 CRAN (R 3.5.1)                       
 readr         1.1.1   2017-05-16 CRAN (R 3.5.1)                       
 rlang         0.2.2   2018-08-16 CRAN (R 3.5.1)                       
 rmarkdown     1.10    2018-06-11 CRAN (R 3.5.1)                       
 rprojroot     1.3-2   2018-01-03 CRAN (R 3.5.0)                       
 rstudioapi    0.8     2018-10-02 CRAN (R 3.5.1)                       
 rvest         0.3.2   2016-06-17 CRAN (R 3.5.1)                       
 scales        1.0.0   2018-08-09 CRAN (R 3.5.1)                       
 stats       * 3.5.1   2018-07-02 local                                
 stringi       1.1.7   2018-03-12 CRAN (R 3.5.0)                       
 stringr       1.3.1   2018-05-10 CRAN (R 3.5.0)                       
 tibble        1.4.2   2018-01-22 CRAN (R 3.5.0)                       
 tools         3.5.1   2018-07-02 local                                
 utils       * 3.5.1   2018-07-02 local                                
 viridisLite   0.3.0   2018-02-01 CRAN (R 3.5.0)                       
 withr         2.1.2   2018-03-15 CRAN (R 3.5.1)                       
 xml2          1.2.0   2018-01-24 CRAN (R 3.5.1)                       
 yaml          2.2.0   2018-07-25 CRAN (R 3.5.1)                       
```

**Comment by wfulp** [comment]
One follow-up note in my testing: I am only able to reproduce this issue when using `row_group_label_position = 'stack'`. When I set it to `identity` the table looks correct.

**Comment by haozhu233** [comment]
@wfulp You found the real cause. Someone contacted me privately before for a very similar issue. The problem is that kableExtra has some mechanism to solve row duplication problem by putting something unique at the beginning of every row. This `row_group_label_position` = "stack" removed the first several columns so the unique part was lost after this step. That's why if you have duplicated rows and you choose `row_group_label_position` = "stack", you will have some issues. 

Unfortunately, this behavior is really hard to fix. I will add some notes in the documentation. In this kind of situation, I guess you can only choose to use the regular collapse_rows method.

**Comment by wfulp** [comment]
Thanks for the response. I will only use stack when I know the row of the table rows will not be duplicated.
