### ISSUE TITLE
\bottomrule at the end of longtable can cause an issue with option repeat_header

### ISSUE THREAD

**Issue by stla** [haozhu233/kableExtra#34]
Hello, 

 LaTeX issue described here: <https://tex.stackexchange.com/questions/384576/longtable-starts-a-second-page-to-print-only-the-bottomrule-line>

`kableExtra` (or `kable`?) generates this code:
```
......
Maserati Bora & 15.0 & 8 & 301.0 & 335 & 3.54 & 3.570 & 14.60 & 0 & 1 & 5 & 8\\
Volvo 142E & 21.4 & 4 & 121.0 & 109 & 4.11 & 2.780 & 18.60 & 1 & 1 & 4 & 2\\
\bottomrule
\end{longtable}
```

The issue is fixed by removing `\bottomrule` and replacing `\endhead`  with 
```
\endhead
\bottomrule
\endfoot
```

**Comment by haozhu233** [comment]
I would have never expected there were so many hidden tricks in longtable. 😂

**Comment by haozhu233** [comment]
Hi, @stla, I think I fixed this problem in the latest version. Could you test it out?

(Somehow I can't reproduce the behavior you reported so I couldn't test if my fix works. It might also be a rnw or windows thing?)

**Comment by stla** [comment]
Hi @haozhu233 
No, sorry, the issue is still there. `\endlastfoot` does not work as expected.

**Comment by haozhu233** [comment]
@stla Hmm, previously I thought it's a sweave or system issue. However, I just tried the tex code you posted in your question on SO on both my Mac and Windows (remotely). It surprised me I couldn't reproduce the behavior you described in either case, even after I made some adjustments on the content length. Is it possible that it's due to your LaTeX setup? Like the longtable version?

**Comment by stla** [comment]
Strange, I don't know. I'm on Windows and I have updated all the packages a few days ago.

The following other solution seems to work (given in a comment by Ulrike Fischer): replace the last `\\` with `\\*\bottomrule`.

**Comment by stla** [comment]
Sorry, I meant the other solution is to replace 
```
...
Volvo 142E & 21.4 & 4 & 121.0 & 109 & 4.11 & 2.780 & 18.60 & 1 & 1 & 4 & 2\\
\bottomrule
\end{longtable}
```
with 
```
....
Volvo 142E & 21.4 & 4 & 121.0 & 109 & 4.11 & 2.780 & 18.60 & 1 & 1 & 4 & 2\\
*\bottomrule
\end{longtable}
```
That is, just replace `\bottomrule` with `*\bottomrule`.

**Comment by stla** [comment]
@haozhu233 , 

 Hello. This issue is back. You removed the `bottomrule` at the end of the table ?:

```
......
115.5 & 111.9 & 3 & 1\\
115.5 & 109.0 & 3 & 1\\
\end{longtable}
```

In my pull request, I fixed this issue by doing 

```
......
115.5 & 111.9 & 3 & 1\\
115.5 & 109.0 & 3 & 1\\
*\bottomrule
\end{longtable}
```

This `bottomrule` does not appear anymore, and the issue is back.

**Comment by haozhu233** [comment]
@stla Can you send me a test document that replicates this bug?

I made some changes to the code to make this feature happen #69. `*\\bottomrule` doesn't work in this case. It will lead to a latex error when rendering.

**Comment by stla** [comment]
Sorry I did some modifications in the code of kableExtra and now I don't manage to reproduce the bug. I will try with the example I posted on tex.stackechange.
Normally there's no error if you do
```
115.5 & 109.0 & 3 & 1\\*\bottomrule
\end{longtable}
```

**Comment by stla** [comment]
Yes, the bug occurs with the code posted on tex.stackexchange: <https://tex.stackexchange.com/questions/384576/longtable-starts-a-second-page-to-print-only-the-bottomrule-line>

**Comment by haozhu233** [comment]
@stla Can you try it out now? I added the * to the last line of contents.

**Comment by stla** [comment]
No, the bug is there. I get this code:
```
Volvo 142E & 21.4 & 4 & 121.0 & 109 & 4.11 & 2.780 & 18.60 & 1 & 1 & 4 & 2\\*
\end{longtable}
```

Why don't you do
```
Volvo 142E & 21.4 & 4 & 121.0 & 109 & 4.11 & 2.780 & 18.60 & 1 & 1 & 4 & 2\\*\bottomrule
\end{longtable}
```
? Does it cause a problem?

**Comment by stla** [comment]
This is the Rnw which yields the bug:

```
\documentclass{article}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage[table]{xcolor}
\begin{document}

<<setup, include=FALSE>>=
library(knitr)
opts_chunk$set(echo=FALSE)
library(kableExtra)
options(knitr.table.format = "latex")
dat <- mtcars
@


a

b

c

d

e

f

\vspace{13pt}


<<results='asis'>>=
kable(dat, booktabs = TRUE, longtable = TRUE, caption = "My table") %>%
  kable_styling(latex_options = c("repeat_header", "striped")) 
@

\end{document}
```

**Comment by haozhu233** [comment]
I re-fixed this issue by inserting a // before \endfoot

**Comment by stla** [comment]
Sorry, I've just seen that I received your message in my spams ! I'll give a try later.

**Comment by stla** [comment]
It works :+1: 
But I don't see the insertion you mention:

```
\begin{longtable}[t]{lrrrrrrrrrrr}
\caption{\label{tab:unnamed-chunk-1}My table}\\
\hiderowcolors
\toprule
  & mpg & cyl & disp & hp & drat & wt & qsec & vs & am & gear & carb\\
\midrule
\endfirsthead
\caption[]{My table \textit{(continued)}}\\
\toprule
  & mpg & cyl & disp & hp & drat & wt & qsec & vs & am & gear & carb\\
\midrule
\endhead
\
\endfoot
\bottomrule
\endlastfoot
```

**Comment by ShanikaLW** [comment]
I ran the following code. It prints unnecessary texts at the end.

```r
long_dt <- rbind(mtcars, mtcars, mtcars)

kable(
  long_dt, 
  format    = "latex", 
  longtable = T, 
  booktabs  = T, 
  caption   = "Longtable"
) %>%
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
  kable_styling(latex_options = c("repeat_header"),
                repeat_header_continued = "\\textit{(Continued on Next Page...)}")

```
