### ISSUE TITLE
Problems with local fonts

### ISSUE THREAD

**Issue by reebop** [haozhu233/kableExtra#437]
**Describe the bug**
There are some problems with local fonts. I use polish fonts. Sometime grouping is not possible if there are words with polish fonts in cells. The same problem is in add_header_above() function. When the table is long then Caption which is repeated doesn't have right fonts.

# code to reproduce the bug.
---
title: "Raport"
author: "RP"
date: "27 10 2019"
header-includes:
   - \usepackage{polski}
output:
  pdf_document:
    number_sections: yes
    latex_engine: xelatex
  word_document: default
mainfont: Century Gothic
always_allow_html: true
---
```{r wsp_smiertelnosci, echo = FALSE, message = FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
library(XLConnect)

wb = loadWorkbook("C:/Docs/Rezerwy/PGNiG/dane/TTZ2018.xls", create = TRUE)
df = readWorksheet(wb, sheet = "TTZ2018", header = T)

kable(df, "latex", longtable = T, booktabs = T, linesep = "", caption = "Współczynniki śmiertelności") %>%
  kable_styling(full_width = F, latex_options = c("hold_position", "repeat_header"), repeat_header_text = "(kont.)")
```
![image](https://user-images.githubusercontent.com/57406998/68224950-e1149580-ffef-11e9-8f56-d26f51de667d.png)
![image](https://user-images.githubusercontent.com/57406998/68224974-f12c7500-ffef-11e9-9d9b-e50b0178f614.png)

**Comment by haozhu233** [comment]
@reebop I think this bug is solved now through https://github.com/haozhu233/kableExtra/pull/440

**Comment by reebop** [comment]
Hi,

Unfortunately the error still exists. Please find the code. The name of the table on first page is ok with proper fonts while the name on the second page of the same table has got wrong fonts.

Kind regards,
Robert

Od: Hao Zhu <notifications@github.com>
Wysłano: wtorek, 11 sierpnia 2020 08:23
Do: haozhu233/kableExtra <kableExtra@noreply.github.com>
DW: reebop <robert.pusz@outlook.com>; Mention <mention@noreply.github.com>
Temat: Re: [haozhu233/kableExtra] Problems with local fonts (#437)


@reebop<https://github.com/reebop> I think this bug is solved now through #440<https://github.com/haozhu233/kableExtra/pull/440>
