### ISSUE TITLE
Error in column_spec_html_cell(target_cell, width, width_min, width_max, : argument "image" is missing, with no default

### ISSUE THREAD

**Issue by lexzhou** [haozhu233/kableExtra#527]
Hi haozhu233, I am currently using the function "column_spec" on my new laptop and I cannot solve this issue... I got this error another day in my old laptop and I ended up solving it by reinstall "kableExtra" package, but it does not work on my new laptop. I also reinstalled the newest version in the R document and the old version of my old laptop but nothing changed. Hope you can help me... Thanks in advance!

My codes are:

for (i in 1:ncol(resultsTable)) {
tTable = tTable %>% column_spec(i+1, background = groupColors[i], include_thead = TRUE) %>%
column_spec(i+1, background = "inherit")
}

Error in column_spec_html_cell(target_cell, width, width_min, width_max, : argument "image" is missing, with no default

**Comment by jciturras** [comment]
Hi,

I'am having the same issue. It appears after the last update.

**Comment by lexzhou** [comment]
> Hi,
> 
> I'am having the same issue. It appears after the last update.

Yeah, It must be... Hope we can have this problem solved soon :)!

**Comment by haozhu233** [comment]
@jciturras @lexzhou Thanks for reporting this bug. It has been fixed in the dev version. 
https://github.com/haozhu233/kableExtra/issues/512

I will push it to CRAN after we finish most of the updates on inline plots.

**Comment by lexzhou** [comment]
> @jciturras @lexzhou Thanks for reporting this bug. In fact, it has been fixed in the dev version a few days ago.
> #512
> 
> If you have an emergent need, please install the dev version.
> 
> I will push the update to CRAN after we finish most of the updates on inline plots.

Thank @haozhu233 for replying us, but I still get the same error by downloading the dev version.

I used `devtools::install_github("haozhu233/kableExtra")()` and  ```
withr::with_envvar(c(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"), 
  remotes::install_github("haozhu233/kableExtra")
)
```

But none of them works... Albeit I have the old laptop, I can still work on it and wait for the update. 
Thanks for the effort 👍

**Comment by lexzhou** [comment]
> Hi,
> 
> I'am having the same issue. It appears after the last update.

Hi jciturras,  could you solve this issue by downloading the dev version? Because I couldn't and I would like to figure out whether that's my problem or the package's.

**Comment by tanthiamhuat** [comment]
so where is the solution for this issue? or do we need to revert back to the older version?

**Comment by vincentarelbundock** [comment]
@tanthiamhuat the package author stated clearly that this was fixed in the development version. You can install it with the `remotes` package:

```r
library(remotes)
install_github("https://github.com/haozhu233/kableExtra")
```

Make sure you restart your R session completely. Then try again.

Have you tried the above already before demanding a fix?

**Comment by tanthiamhuat** [comment]
yes, I confirm that I perform the above 2 lines, restart my R session completely, and I get the same error:
Error in column_spec_html_cell(target_cell, width, width_min, width_max,  : 
  argument "image" is missing, with no default
Prior to the 1.2.1 version, I do not have such issue.
How can I revert to the old version?

**Comment by vincentarelbundock** [comment]
Sorry to hear about that. There are instructions for installing old versions of packages on many websites. Here is one:

https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages

**Comment by tanthiamhuat** [comment]
Can I know the previous version number prior to 1.2.1?

**Comment by vincentarelbundock** [comment]
The CRAN page for kableExtra has an Archive of all previous versions.

**Comment by tanthiamhuat** [comment]
the error arise from :
column_spec(1:6, background = white, color = yellow, include_thead = TRUE)
if I omit that "include_thead = TRUE", then there is no error, but I do not get the correct color I want.
even I revert back to the version 1.1.0, it gives the same error. I am not sure why, because previously it works.

**Comment by lexzhou** [comment]
> the error arise from :
> column_spec(1:6, background = white, color = yellow, include_thead = TRUE)
> if I omit that "include_thead = TRUE", then there is no error, but I do not get the correct color I want.
> even I revert back to the version 1.1.0, it gives the same error. I am not sure why, because previously it works.

I guess it is not about the version. I had transferred my old packages archive,  which was version 3.6, to my new one but did not work either. Tried many ways but cannot do anything :(

**Comment by tanthiamhuat** [comment]
the authors of package "kableExtra" should ensure that new version works well before release, not have additional issues.

**Comment by vincentarelbundock** [comment]
@tanthiamhuat I am NOT one of the authors of the package and am in no way speaking for them. However, I feel it is important to remind people that this software is produced by volunteer (free) work. The authors surely do their best to limit the number of bugs, but they are inevitable. Of course, everyone would like bug free code (does such a thing exist), but please be considerate toward the authors.

**Comment by haozhu233** [comment]
Fixed now. 

@vincentarelbundock Thanks a lot for giving a hand here! 👍 I had conference deadlines due, which just consumed too much of my time. (but it's all good now)

@tanthiamhuat Hey, come and read the MIT license: 

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Also, 21 emails. I think I'm patient enough to wait until the 20th email before I suggested you to check for community help. So you just come here and talk like this?
<img width="501" alt="Screen Shot 2020-10-03 at 8 02 03 AM" src="https://user-images.githubusercontent.com/7014590/94991136-f1f6bf80-054e-11eb-8ad2-854cec312a83.png">

**Comment by tanthiamhuat** [comment]
https://davidgohel.github.io/flextable/articles/offcran/examples.html   
for those having issues, you can consider flextable as an alternative.

**Comment by carlosortegap** [comment]
How was it fixed?

**Comment by haozhu233** [comment]
It's fixed in the github version. I will push it to cran soon.

**Comment by carlosortegap** [comment]
> It's fixed in the github version. I will push it to cran soon.

Thanks!
